// Icon mapping from Lucide to React Icons Material Design (more colorful and detailed 2D icons)
import {
  MdHome,
  MdLocalShipping,
  MdInventory2,
  MdChatBubbleOutline,
  MdPerson,
  MdLogout,
  MdMenu,
  MdClose,
  MdSecurity,
  MdBarChart,
  MdPeople,
  MdDescription,
  MdNotifications,
  MdSearch,
  MdAdd,
  MdHistory,
  MdTrendingUp,
  MdChevronLeft,
  MdChevronRight,
  MdArrowForward,
  MdLocationOn,
  MdCalendarToday,
  MdScale,
  MdEuro,
  MdStar,
  MdCheckCircle,
  MdCancel,
  MdSchedule,
  MdVisibility,
  MdPhone,
  MdEmail,
  MdVerified,
  MdBlock,
  MdPlayArrow,
  MdPause,
  MdDelete,
  MdEdit,
  MdMoreVert,
  MdExplore,
  MdStraighten,
  MdWarning,
  MdAutoAwesome,
  MdWorkspacePremium,
  MdBolt,
  MdPublic,
  MdExpandMore,
  MdFilterList,
  MdSwapVert,
  MdAttachFile,
  MdSend,
  MdRoute,
  MdArrowBack,
  MdAttachMoney,
  MdVisibilityOff,
  MdLock,
  MdLockOpen,
  MdInfo,
  MdError,
  MdSave,
  MdCameraAlt,
  MdCloudUpload,
  MdRefresh,
  MdHelpOutline,
  MdBook,
  MdCheck,
  MdDirectionsCar,
  MdGpsFixed,
  MdFavorite,
  MdCookie,
  MdSettings,
} from "react-icons/md"
import {
  FaFacebook,
  FaTwitter,
  FaLinkedin,
  FaInstagram,
  FaYoutube,
} from "react-icons/fa"

// Export icon mappings - Material Design icons are more colorful and modern
export const Icons = {
  // Navigation
  Home: MdHome,
  Truck: MdLocalShipping,
  Package: MdInventory2,
  MessageCircle: MdChatBubbleOutline,
  User: MdPerson,
  LogOut: MdLogout,
  Menu: MdMenu,
  X: MdClose,
  
  // Admin
  Shield: MdSecurity,
  BarChart3: MdBarChart,
  Users: MdPeople,
  FileText: MdDescription,
  
  // Actions
  Bell: MdNotifications,
  Search: MdSearch,
  Plus: MdAdd,
  History: MdHistory,
  TrendingUp: MdTrendingUp,
  ChevronLeft: MdChevronLeft,
  ChevronRight: MdChevronRight,
  ArrowRight: MdArrowForward,
  ChevronDown: MdExpandMore,
  
  // Location & Time
  MapPin: MdLocationOn,
  Calendar: MdCalendarToday,
  
  // Items
  Weight: MdScale,
  Euro: MdEuro,
  Star: MdStar,
  CheckCircle: MdCheckCircle,
  XCircle: MdCancel,
  Clock: MdSchedule,
  Eye: MdVisibility,
  Phone: MdPhone,
  Mail: MdEmail,
  
  // Status
  UserCheck: MdVerified,
  UserX: MdBlock,
  
  // Media
  Play: MdPlayArrow,
  Pause: MdPause,
  
  // Actions
  Trash2: MdDelete,
  Edit: MdEdit,
  MoreVertical: MdMoreVert,
  
  // Additional icons
  Navigation: MdExplore,
  Ruler: MdStraighten,
  AlertCircle: MdWarning,
  Sparkles: MdAutoAwesome,
  Award: MdWorkspacePremium,
  Zap: MdBolt,
  Globe: MdPublic,
  Route: MdRoute,
  MessageSquare: MdChatBubbleOutline,
  Send: MdSend,
  Paperclip: MdAttachFile,
  Filter: MdFilterList,
  ArrowUpDown: MdSwapVert,
  ArrowLeft: MdArrowBack,
  DollarSign: MdAttachMoney,
  EyeOff: MdVisibilityOff,
  Lock: MdLock,
  Unlock: MdLockOpen,
  Info: MdInfo,
  AlertTriangle: MdError,
  Save: MdSave,
  Camera: MdCameraAlt,
  Upload: MdCloudUpload,
  RefreshCw: MdRefresh,
  Facebook: FaFacebook,
  Twitter: FaTwitter,
  Linkedin: FaLinkedin,
  Instagram: FaInstagram,
  Youtube: FaYoutube,
  Scale: MdStraighten,
  HelpCircle: MdHelpOutline,
  Book: MdBook,
  Check: MdCheck,
  Car: MdDirectionsCar,
  Target: MdGpsFixed,
  Heart: MdFavorite,
  Cookie: MdCookie,
  Settings: MdSettings,
}

// Re-export all icons for direct use (named exports for compatibility)
export const {
  Home,
  Truck,
  Package,
  MessageCircle,
  User,
  LogOut,
  Menu,
  X,
  Shield,
  BarChart3,
  Users,
  FileText,
  Bell,
  Search,
  Plus,
  History,
  TrendingUp,
  ChevronLeft,
  ChevronRight,
  ArrowRight,
  ChevronDown,
  MapPin,
  Calendar,
  Weight,
  Euro,
  Star,
  CheckCircle,
  XCircle,
  Clock,
  Eye,
  Phone,
  Mail,
  UserCheck,
  UserX,
  Play,
  Pause,
  Trash2,
  Edit,
  MoreVertical,
  Navigation,
  Ruler,
  AlertCircle,
  Sparkles,
  Award,
  Zap,
  Globe,
  Route,
  MessageSquare,
  Send,
  Paperclip,
  Filter,
  ArrowUpDown,
  ArrowLeft,
  DollarSign,
  EyeOff,
  Lock,
  Unlock,
  Info,
  AlertTriangle,
  Save,
  Camera,
  Upload,
  RefreshCw,
  Facebook,
  Twitter,
  Linkedin,
  Instagram,
  Youtube,
  Scale,
  HelpCircle,
  Book,
  Check,
  Car,
  Target,
  Heart,
  Cookie,
  Settings,
} = Icons

export default Icons
